const a=4;
const b=6;
console.log(a,b,a+b);
console.log('%s',a);
console.log('Hi Lauraence');
console.count('Test'+a);
console.count('Test'+a);
console.count('Test'+a);
console.clear();
console.log('Hi Laurance');
console.warn('warn');
console.info('info');
console.table([{a:1,b:2},{a:5,b:10}]);